name: Parallel Cypress Tests

on:
  pull_request:
    branches:
    - develop
    - version-12-hotfix
    - version-11-hotfix

jobs:
  test:
    name: Cypress run
    runs-on: macos-latest

    strategy:
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Redis
        uses: shogo82148/actions-setup-redis@v1

      - name: Install Mariadb
        run: |
          brew install mariadb
          mysql_install_db
          mysql.server start

      - name: Setup Database
        run: |
          sudo mysql -u root -e "SET GLOBAL character_set_server = 'utf8mb4'";
          sudo mysql -u root -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'";
          sudo mysql -u root -e "CREATE DATABASE test_frappe_consumer";
          sudo mysql -u root -e "CREATE USER 'test_frappe_consumer'@'localhost' IDENTIFIED BY 'test_frappe_consumer'";
          sudo mysql -u root -e "GRANT ALL PRIVILEGES ON \`test_frappe_consumer\`.* TO 'test_frappe_consumer'@'localhost'";

          sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'travis'; FLUSH PRIVILEGES";

      - name: install bench
        run: |
          cd $HOME
          pip install frappe-bench

      - name: init bench
        run: |
          echo $HOME
          cd $HOME
          ls -l $GITHUB_WORKSPACE
          bench init frappe-bench --skip-assets --python $(which python) --frappe-path $GITHUB_WORKSPACE

          mkdir $HOME/frappe-bench/sites/test_site
          cp $GITHUB_WORKSPACE/.travis/consumer_db/mariadb.json $HOME/frappe-bench/sites/test_site/site_config.json

      - name: Run test
        run: |
          cd $HOME/frappe-bench
          bench setup requirements --node;
          bench start &
          bench --site test_site --force reinstall --yes
          bench build --app frappe
          bench --site test_site execute frappe.utils.install.complete_setup_wizard
          bench --site test_site run-ui-tests frappe --headless --parallel --ci-build-id $GITHUB_RUN_ID
